name: expense_tracker_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.3+4

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  fl_chart: ^0.66.2
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  firebase_core: ^2.27.2
  firebase_auth: ^4.18.0
  cloud_firestore: ^4.15.10
  get_it: ^7.6.7
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  sign_in_button: ^3.2.0
  uuid: ^4.3.3
  google_sign_in: ^6.2.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  image_path : "assets/icons/expends_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/expends_icon.png

  
