// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class StagingFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeml0n3gDi6Iy4Q02lp1t_r3NX2YYZLjI',
    appId: '1:636141818622:android:6f0ef52eb8e7f0d7c04baf',
    messagingSenderId: '636141818622',
    projectId: 'expends-staging',
    storageBucket: 'expends-staging.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOW1NrgzW-zYI7jIgifwHhsjr0-ffeUIU',
    appId: '1:636141818622:ios:97d311890892e160c04baf',
    messagingSenderId: '636141818622',
    projectId: 'expends-staging',
    storageBucket: 'expends-staging.appspot.com',
    androidClientId:
        '636141818622-jcihjsm7hhuq0a0vd5sl6mmq2d43v8lr.apps.googleusercontent.com',
    iosClientId:
        '636141818622-6e09enifmf202fifgmnvk4hgj3t6rlod.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTrackerApp',
  );
}
